version: '3'

services:
  flask-app:
    container_name: ppp-project-2
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database credentials
      DATABASE_URL_DOCKER: ${DATABASE_URL_DOCKER}
    restart: always
    depends_on:
      # build those images first
      - mysql
    links:
      # network connection with these services
      - mysql
    ports:
      # local port: container port
      - '5000:5000'
    volumes:
      - ./app:/app

  mysql:
    container_name: flask_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33060:3306'
    # Where our data will be persisted
    volumes:
      # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql

# Names our volume
volumes:
  # just a persistance data
  mysql-data:
    driver: local
