version: '3'

services:
  flask-app:
    container_name: ppp-project-2
    build:
      #app
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database credentials
      DATABASE_URL: mysql+pymysql://pyrates:iamyourcaptain@dbserver/pyrates pyrates:latest
    restart: always
    depends_on:
      # build those images first
      - mysql
    links:
      # network connection with these services
      - mysql
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app

  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iamyourcaptain
      MYSQL_DATABASE: pyrates
      MYSQL_USER: pyrates
      MYSQL_PASSWORD: iamyourcaptain
    ports:
      - '3307:3307'
    volumes:
      # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql

volumes:
  # just a persistance data
  mysql-data:
    driver: local
