version: '3'

services:
  flask-app:
    container_name: ppp-project-2
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database credentials
      DATABASE_URL_DOCKER: ${DATABASE_URL_DOCKER}
    restart: always
    depends_on:
      # build those images first
      - mysql
    links:
      # network connection with these services
      - mysql
    ports:
      # local port: container port
      - '5000:5000'
    volumes:
      - ./app:/app

  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    # Compose supports declaring default environment variables in an environment file named .env
    # Don't believe me? Run this command: docker exec mysql env | grep MYSQL_ROOT_PASSWORD | cut -d'=' -f2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '7777:3306'
      # Where our data will be persisted
    volumes:
      # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql

# Names our volume
volumes:
  # just a persistance data
  mysql-data:
    driver: local
