"""update users and coin table

Revision ID: 7ff222e91bc5
Revises: e64fd93bd625
Create Date: 2022-04-26 22:33:26.648384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ff222e91bc5"
down_revision = "e64fd93bd625"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin_name", sa.String(length=64), nullable=True),
        sa.Column("ticker_name", sa.String(length=120), nullable=True),
        sa.Column(
            "price_usd", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column(
            "usd_market_cap", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column(
            "usd_24hr_vol", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column(
            "usd_24hr_change", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column("last_api_query_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coin_coin_name"), "coin", ["coin_name"], unique=True
    )
    op.create_index(
        op.f("ix_coin_last_updated_at"),
        "coin",
        ["last_updated_at"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "user_coins",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["coin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "coin_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_coins")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_coin_last_updated_at"), table_name="coin")
    op.drop_index(op.f("ix_coin_coin_name"), table_name="coin")
    op.drop_table("coin")
    # ### end Alembic commands ###
