# Runs all tests from tests directory

name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Install python dependencies
        run: pip install --upgrade pip
        run: pip install poetry==1.1.12

      
      - name: Running tests
        run: poetry run pytest tests/test*
